server:
  port: 7988
spring:
  application:
    name: activiti8_workflow
  datasource:
    hikari:
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://IP:PORT/activiti8?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
  activiti:
    database-schema-update: true
    deployment-mode: never-fail # 关闭 SpringAutoDeployment
    check-process-definitions: false # 自动部署验证设置:true-开启（默认）、false-关闭
    # 日志的相关配置
    history-level: full
    db-history-used: true